### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by billymohajeri** [billymohajeri/Recipe-App#11]
Hi,

We are a team of 2 members: @billymohajeri and @leehaney254 
Team member A: @leehaney254 
Team member B: @billymohajeri 

[Link](https://github.com/users/billymohajeri/projects/5/views/1) to the project

**Comment by jerryowusu** [comment]
Hi Team, 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost got it](https://user-images.githubusercontent.com/65233860/232421834-34e32647-d6ba-40da-a374-9583452be83a.gif)



## Highlights
:heavy_check_mark: Provided a valid link 
:heavy_check_mark: Added all required columns to the board

## Required Changes ♻️

- [ ] Each project requirement should have at least one corresponding card in the Kanban board. However, I see that there is no corresponding cards for the first two project requirements as highlighted in the image below. Kindly update your kanban board accordingly. :pray: 

![Screenshot from 2023-04-17 07-54-31](https://user-images.githubusercontent.com/65233860/232421327-e48cf237-c4c5-45fc-81ee-c79f63335a5e.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by billymohajeri** [comment]
Thank you, we updated card number 2 to resolve this issue.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/58295348/232424132-2ea49102-e25e-4c50-b752-1475daf72a08.png">

**Comment by Olamarx** [comment]
> Thank you, we updated card number 2 to resolve this issue. <img alt="image" width="881" src="https://user-images.githubusercontent.com/58295348/232424132-2ea49102-e25e-4c50-b752-1475daf72a08.png">

Hi @billymohajeri, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>
## Highlights
- Kanban setup ✔️ 
- All cards ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
